future: true
title: Anchorboot
description: Platform firmware distribution for ARM-based ChromeOS devices
logo: anchorboot.svg
show_downloads: false
github:
  is_project_page: true
  is_user_page: false
  repository_url: https://github.com/anchorboot/
  owner_url: https://github.com/alpernebbi/
  owner_name: Alper Nebi Yasak
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
