future: true
title: Anchorboot
description: Platform firmware distribution for ARM-based ChromeOS devices
logo: anchorboot.svg
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
